#781 Excude inactice users from notifications
velis74/django-project-base pull request #130
Opened 2023-09-25 05:20 UTC by KlemenSpruk

2023-09-25 11:19 UTC, velis74 requested changes
unit tests, docs

2023-09-25 11:19 UTC, velis74 commented on vue/components/notifications-editor.vue
> +const consumerUrl: string = (props.consumerUrl !== undefined ? props.consumerUrl : 'notification') as string;
Za tole imaš DetailViewApi, sploh še s pull requestom, ki dodaja še search parametre.

2023-09-26 06:34 UTC, KlemenSpruk commented on vue/components/notifications-editor.vue
> +const consumerUrl: string = (props.consumerUrl !== undefined ? props.consumerUrl : 'notification') as string;
tukaj ne rabim detail api view

2023-09-26 06:45 UTC, KlemenSpruk commented
Plugin za coverage ne dela. 

Run coverage run -m unittest discover tests/
EEEEEEEEEE
======================================================================

2023-09-26 07:07 UTC, velis74 commented on vue/components/notifications-editor.vue
> +const consumerUrl: string = (props.consumerUrl !== undefined ? props.consumerUrl : 'notification') as string;
Sem samo predlagal, ker si kuril 20 vrstic kode, namesto treh.
Coverage check ti odleti, doddaj kak unit test.

2023-09-26 07:22 UTC, KlemenSpruk commented
pr popravljen

2023-09-26 07:38 UTC, velis74 approved these changes

2023-09-26 07:44 UTC, merged