#12 Users editor: invite new user
velis74/django-project-base pull request #137
Opened 2023-10-04 09:03 UTC by KlemenSpruk

2023-10-04 11:15 UTC, velis74 requested changes

2023-10-04 11:15 UTC, velis74 commented on django_project_base/base/models.py
> +
role? invitation text? JSONField za custom parametre?

2023-10-04 11:15 UTC, velis74 commented on django_project_base/notifications/email_notification.py
> +class EMailNotificationWithListOfEmails(EMailNotification):
Zakaj nov class tu? A ni že standardni EmailNotification sposoben pokriti pošiljanja večim ljudem?

2023-10-04 11:15 UTC, velis74 commented on django_project_base/notifications/email_notification.py
> +        from django_project_base.notifications.base.channels.mail_channel import MailChannel
tule bi pa tudi pričakoval, da ta notification samo v zanki kliče splošnega za en mail? Ni tu malo veliko kode? DRY?

2023-10-04 11:15 UTC, velis74 commented on example/demo_django_base/migrations/0008_projectinvite.py
> +    project_sett = swapper.load_model("django_project_base", "ProjectSettings")
To sva že obdelala. apps.get_model...

2023-10-04 11:15 UTC, velis74 commented on django_project_base/base/models.py
> +    send_by = models.ForeignKey(
invited_by ali (precej slabše) sent_by.

2023-10-05 06:17 UTC, KlemenSpruk commented on example/demo_django_base/migrations/0008_projectinvite.py
> +    project_sett = swapper.load_model("django_project_base", "ProjectSettings")
popravljeno

2023-10-05 06:17 UTC, KlemenSpruk commented on django_project_base/base/models.py
> +    send_by = models.ForeignKey(
popravljeno

2023-10-05 06:18 UTC, KlemenSpruk commented on django_project_base/base/models.py
> +
role dodan, invitation text se nastavi v settings, custom parametrov še ni dodanih-ni use cases v dpb

2023-10-05 06:19 UTC, KlemenSpruk commented on django_project_base/notifications/email_notification.py
> +class EMailNotificationWithListOfEmails(EMailNotification):
Je, amak tukaj se posilja neobstojećim userjem, zato dodelava

2023-10-05 08:12 UTC, KlemenSpruk commented on django_project_base/notifications/email_notification.py
> +        from django_project_base.notifications.base.channels.mail_channel import MailChannel
popravljeno

2023-10-05 10:33 UTC, KlemenSpruk commented
PR ima popravljene vse komentarje in predelan na funcionalnosti ki so zjutraj manjkale

2023-10-05 11:52 UTC, KlemenSpruk commented
Dodana rola na invite

2023-10-05 12:00 UTC, velis74 approved these changes

2023-10-06 12:09 UTC, velis74 approved these changes

2023-10-06 12:11 UTC, merged